workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean project
        script: flutter clean

      - name: Get packages
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa