workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: 3.24.0
      xcode: latest

    scripts:
      - flutter clean
      - flutter pub get

      - cd ios
      - rm -rf Pods Podfile.lock
      - pod install
      - cd ..

      - flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa