// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1KrXCu5HWCJ8lGisOftG10tOVIRtOskc',
    appId: '1:1032047333639:web:c2f3236af6e003cf4235a2',
    messagingSenderId: '1032047333639',
    projectId: 'smartmealaii',
    authDomain: 'smartmealaii.firebaseapp.com',
    storageBucket: 'smartmealaii.firebasestorage.app',
    measurementId: 'G-RL7T4STSEC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd6qbQ9G5gyjFThN_I7HAGWA4HW-xbZq8',
    appId: '1:1032047333639:android:0ac034d14af716a14235a2',
    messagingSenderId: '1032047333639',
    projectId: 'smartmealaii',
    storageBucket: 'smartmealaii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo18Oz_IvKpIE6fyUbfbzQh9DL_CN37Vg',
    appId: '1:1032047333639:ios:ba003b475adffa624235a2',
    messagingSenderId: '1032047333639',
    projectId: 'smartmealaii',
    storageBucket: 'smartmealaii.firebasestorage.app',
    iosBundleId: 'com.example.smartmealAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo18Oz_IvKpIE6fyUbfbzQh9DL_CN37Vg',
    appId: '1:1032047333639:ios:ba003b475adffa624235a2',
    messagingSenderId: '1032047333639',
    projectId: 'smartmealaii',
    storageBucket: 'smartmealaii.firebasestorage.app',
    iosBundleId: 'com.example.smartmealAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1KrXCu5HWCJ8lGisOftG10tOVIRtOskc',
    appId: '1:1032047333639:web:cd406d877e33d8754235a2',
    messagingSenderId: '1032047333639',
    projectId: 'smartmealaii',
    authDomain: 'smartmealaii.firebaseapp.com',
    storageBucket: 'smartmealaii.firebasestorage.app',
    measurementId: 'G-8T2MDBJ8RE',
  );
}
